package com.sashia.ecommerce.media;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;
import java.util.Map;

/**
 * A stored file (image, ...) plus its lifecycle state.
 *
 * <p>Lifecycle: every upload starts as {@link MediaStatus#DRAFT}. It becomes {@link MediaStatus#SAVED}
 * when it is attached to a resource (product, user, service). The bytes never move on disk when the
 * status changes, so "saving" a draft is a single database update.</p>
 */
@Getter
@Setter
@Entity
@Table(name = "media", schema = "media")
public class Media {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Public file name: {@code <uuid>.<ext>}. Generated by the server, unique. */
    private String slug;

    /** Where the bytes live inside the storage (relative key, never an absolute path). */
    private String storageKey;

    /** File name sent by the client. Display only, never used to build a path. */
    private String originalName;

    /** SHA-256 hex of the content. */
    private String checksum;

    @Enumerated(EnumType.STRING)
    private MediaStatus status;

    /** Null while the draft is not bound to a resource yet. Set together with {@link #resourceId}. */
    @Enumerated(EnumType.STRING)
    private MediaResourceType resourceType;

    private Long resourceId;

    /** User who uploaded the file. */
    private Long ownerId;

    /** Detected from the file content, not from the client. */
    private String mimeType;

    private String extension;

    private Long size;

    private Integer displayOrder = 0;

    @JdbcTypeCode(SqlTypes.JSON)
    private Map<String, Object> metadata;

    private String description;

    @CreationTimestamp
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;

    /* *********************************** HELPERS ************************************ */

    public boolean isDraft() {
        return status == MediaStatus.DRAFT;
    }

    public boolean belongsTo(MediaResourceType type, Long id) {
        return resourceType == type && resourceId != null && resourceId.equals(id);
    }

}
