package com.sashia.ecommerce.media.internal;

import com.sashia.shared.exception.ResourceNotFoundException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.DigestInputStream;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;

@Component
class LocalMediaStorage implements MediaStorage {

    private static final Logger log = LoggerFactory.getLogger(LocalMediaStorage.class);

    private final Path root;

    LocalMediaStorage(MediaProperties properties) {
        this.root = properties.root().toAbsolutePath().normalize();
    }

    @Override
    public StoredFile store(String key, InputStream content) throws IOException {
        Path target = resolve(key);
        Files.createDirectories(target.getParent());

        MessageDigest digest = newDigest();
        Path tmp = Files.createTempFile(target.getParent(), ".upload-", ".tmp");
        try {
            long size;
            try (DigestInputStream in = new DigestInputStream(content, digest)) {
                size = Files.copy(in, tmp, StandardCopyOption.REPLACE_EXISTING);
            }
            Files.move(tmp, target, StandardCopyOption.ATOMIC_MOVE);
            return new StoredFile(HexFormat.of().formatHex(digest.digest()), size);
        } finally {
            Files.deleteIfExists(tmp);
        }
    }

    @Override
    public Resource load(String key) {
        Path file = resolve(key);
        if (!Files.isRegularFile(file) || !Files.isReadable(file))
            throw new ResourceNotFoundException("media.file.not.found");
        return new FileSystemResource(file);
    }

    @Override
    public void delete(String key) {
        try {
            Files.deleteIfExists(resolve(key));
        } catch (IOException | RuntimeException e) {
            log.error("MEDIA_DELETE_FAILED: {}", key, e);
        }
    }

    // =============================== HELPERS ===============================

    /** Keys are generated by the server, but the check keeps a corrupted row from escaping the root. */
    private Path resolve(String key) {
        Path path = root.resolve(key).normalize();
        if (!path.startsWith(root) || path.equals(root))
            throw new IllegalArgumentException("Storage key escapes the storage root");
        return path;
    }

    private static MessageDigest newDigest() {
        try {
            return MessageDigest.getInstance("SHA-256");
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException(e);
        }
    }

}
